# General ---------------------------------------------------------------------

repo_type: "python_test" # "python_lite", "python_test", "python_build", "Fiji" 
python_version: "3.11"

# Readme ----------------------------------------------------------------------

instructions: "python" # "python", "fiji", "none"

# Tests -----------------------------------------------------------------------

tested_python: "['3.9', '3.10', '3.11']"
tested_os: "[ubuntu-latest, windows-latest, macos-latest]"