name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: {{ os_versions }}
        python-version: {{ python_versions }}

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with: 
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run tests
      run: |
        pytest

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Update README Python badge" || true
        git pull --rebase
        git push